a = input('Digite algo: ')
print('-'*40)
print('O Tipo Primitivo desse valor é', type(a))
print('Só tem espaços? ', a.isspace())
print('É um Numero? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Esta em em maisculas?', a.isupper())
print('Esta em minusculo? ', a.islower())
print('Esta Capitalizada? ', a.istitle())
print('-'*40)

